### ISSUE TITLE
Collision bugs out if having low fps

### ISSUE THREAD

**Issue by 3elDU** [vectozavr/minecraft_3dzavr#1]
If I have <5 fps, collision bugs out and my character just won't collide with the floor, which you can see on the video:
[https://youtu.be/qo9n-LNGRyk](https://youtu.be/qo9n-LNGRyk)

Edit:
It also bugs if you drag the window for too long.

**Comment by vectozavr** [comment]
This problem happens due-to the character displacement becomes bigger with low fps, so there is a moment when the vertical displacement is equal to the players height hence we can't detect the collision. To correct this we should check if fps is smaller than some particular number and make several iterations of physics update with fixed time step.

Maybe, I will handle this in future, but most probably this problem will disappear when I will use Vulcan or openGL instead of soft rendering.

**Comment by 3elDU** [comment]
You can calculate the maximum deltaTime value, when player will still collide with the walls, and just clamp the deltaTime variable between minimum value and calculated maximum. So even when fps will be very low, collision will work fine.

**Comment by vectozavr** [comment]
I solved this problem in my last commit. I just don't allow _deltaTime to be smaller than 1/10 (10 fps).
